In [1]:
import pandas as pd
import numpy as np

In [2]:
 obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a',
'c'])

In [3]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [4]:
obj2 = obj.reindex(list('abcde'))

In [5]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [6]:
 obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2,
4])

In [7]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [10]:
obj3.reindex(range(5),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
dtype: object

In [11]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
index=['a', 'c', 'd'],
columns=['Ohio', 'Texas',
'California'])

In [12]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [15]:
frame2 = frame.reindex(list('abcd'),method='ffill')

In [16]:
frame2

Ohio  Texas  California
a     0      1           2
b     0      1           2
c     3      4           5
d     6      7           8

In [17]:
states = ['Texas', 'Utah', 'California']

In [18]:
frame2.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [19]:
t = frame2.reindex(columns=states)

In [20]:
t['a'] =1

In [21]:
t

Texas  Utah  California  a
a      1   NaN           2  1
b      1   NaN           2  1
c      4   NaN           5  1
d      7   NaN           8  1

In [22]:
frame2

Ohio  Texas  California
a     0      1           2
b     0      1           2
c     3      4           5
d     6      7           8

In [23]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd',
'e'])

In [24]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [25]:
new_obj = obj.drop('c')

In [26]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [28]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
columns=['one', 'two', 'three',
'four'])

In [29]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [31]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [32]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [33]:
data.drop(columns='two')

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [34]:
data.drop(columns='two',inplace=True)

In [36]:
data

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [37]:
 obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [38]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [39]:
obj['b']

1.0

In [40]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [41]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [42]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [43]:
obj['b':'c'] = 5

In [44]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [45]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
columns=['one', 'two', 'three',
'four'])

In [46]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [47]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [48]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [53]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [54]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [55]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [56]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [57]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [58]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [59]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [60]:
 data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [64]:
data.iloc[:,:3][data .three < 9]

one  two  three
Ohio        0    1      2
Colorado    4    5      6

In [62]:
data.iloc[:,:3]

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [63]:
[data .three > 5]

[Ohio        False
 Colorado     True
 Utah         True
 New York     True
 Name: three, dtype: bool]

In [65]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [71]:
data.iloc[1,1]

5

In [72]:
ser = pd.Series(np.arange(3.))

In [74]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [75]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [76]:
ser2[-1]

2.0

In [78]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [79]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd',
'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])

In [80]:
s1,s2

(a    7.3
 c   -2.5
 d    3.4
 e    1.5
 dtype: float64, a   -2.1
 c    3.6
 e   -1.5
 f    4.0
 g    3.1
 dtype: float64)

In [81]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [82]:
s1.add(s2,fill_value=0)

a    5.2
c    1.1
d    3.4
e    0.0
f    4.0
g    3.1
dtype: float64

In [83]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),
columns=list('bcd'),
index=['Ohio', 'Texas', 'Colorado'])

In [84]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
columns=list('bde'),
index=['Utah', 'Ohio', 'Texas',
'Oregon'])

In [85]:
df1,df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [86]:
df1.add(df2,fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [87]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
columns=list('abcd'))

In [88]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
columns=list('abcde'))

In [89]:
df2.loc[1, 'b'] = np.nan

In [90]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [91]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [92]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [93]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [94]:
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [95]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [96]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [97]:
arr = np.arange(12.).reshape((3, 4))


In [98]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [99]:
arr[0]

array([0., 1., 2., 3.])

In [100]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [101]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
columns=list('bde'),
index=['Utah', 'Ohio', 'Texas',
'Oregon'])

In [102]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [105]:
frame - frame.iloc[0]

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [106]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [107]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [108]:
series3 = frame['d']

In [109]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [112]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [114]:
frame.values

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [115]:
frame = pd.DataFrame(np.random.randn(4, 3),
columns=list('bde'),
index=['Utah', 'Ohio', 'Texas',
'Oregon'])

In [116]:
frame

b         d         e
Utah    0.461568  1.144868 -0.023796
Ohio   -0.211013 -0.017584  0.775530
Texas   0.354119  0.695202  0.519504
Oregon -1.000656 -0.186399 -0.674042

In [117]:
import numpy as np

In [118]:
np.abs(frame)

b         d         e
Utah    0.461568  1.144868  0.023796
Ohio    0.211013  0.017584  0.775530
Texas   0.354119  0.695202  0.519504
Oregon  1.000656  0.186399  0.674042

In [119]:
f = lambda x: x.max() - x.min()

In [124]:
frame.apply(f,axis='index')

b    1.462224
d    1.331267
e    1.449572
dtype: float64

In [125]:
f = lambda x: pd.Series([x.min(),x.max()],index=['min','max'])

In [129]:
frame.apply(f,axis=1)

min       max
Utah   -0.023796  1.144868
Ohio   -0.211013  0.775530
Texas   0.354119  0.695202
Oregon -1.000656 -0.186399

In [132]:
format = lambda i: '%.2f' % i

In [133]:
frame.applymap(format)

b      d      e
Utah     0.46   1.14  -0.02
Ohio    -0.21  -0.02   0.78
Texas    0.35   0.70   0.52
Oregon  -1.00  -0.19  -0.67

In [134]:
frame['b'].map(format)

Utah       0.46
Ohio      -0.21
Texas      0.35
Oregon    -1.00
Name: b, dtype: object

In [135]:
obj = pd.Series(range(4),index=list('dabc'))

In [136]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [137]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
index=['three', 'one'],
columns=['d', 'a', 'b', 'c'])

In [140]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [141]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [142]:
obj = pd.Series([4, 7, -3, 2])

In [143]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [144]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [145]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0,
1]})

In [146]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [147]:
frame.sort_values(by=['b'])

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [148]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [158]:
obj = pd.Series([7, -5,-5, 7, 4, 2, 0, 4,4])

In [159]:
obj.rank()

0    8.5
1    1.5
2    1.5
3    8.5
4    6.0
5    4.0
6    3.0
7    6.0
8    6.0
dtype: float64

In [160]:
obj.shape

(9,)

In [156]:
obj.unique().shape

(5,)

In [161]:
obj.rank(method='first')

0    8.0
1    1.0
2    2.0
3    9.0
4    5.0
5    4.0
6    3.0
7    6.0
8    7.0
dtype: float64

In [165]:
obj.rank(ascending=False,method='min')

0    1.0
1    8.0
2    8.0
3    1.0
4    3.0
5    6.0
6    7.0
7    3.0
8    3.0
dtype: float64

In [166]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0,
1],'c': [-2, 5, 8, -2.5]})

In [167]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [173]:
frame.rank(axis=0,method = 'dense')

a    b    c
0  1.0  3.0  2.0
1  2.0  4.0  3.0
2  1.0  1.0  4.0
3  2.0  2.0  1.0

In [174]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [176]:
obj.index.is_unique

False

In [177]:
obj.a

a    0
a    1
dtype: int64

In [178]:
obj.c

4

In [179]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a',
'b', 'b'])

In [181]:
df

0         1         2
a -0.049437  0.167548  0.475148
a  1.213460  1.225425 -0.999275
b  0.514109 -0.141164 -1.296492
b  1.710104 -0.199271 -0.534090

In [184]:
df.loc['a',:]

0         1         2
a -0.049437  0.167548  0.475148
a  1.213460  1.225425 -0.999275

In [185]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
[np.nan, np.nan], [0.75, -1.3]],
index=['a', 'b', 'c', 'd'],
columns=['one', 'two'])

In [186]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [187]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [189]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [191]:
df.sum(axis='columns',skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [193]:
df.idxmax(axis=1)

a    one
b    one
c    NaN
d    one
dtype: object

In [194]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [196]:
df.cummax()

one  two
a  1.4  NaN
b  7.1 -4.5
c  NaN  NaN
d  7.1 -1.3

In [197]:
df.cummin()

one  two
a  1.40  NaN
b  1.40 -4.5
c   NaN  NaN
d  0.75 -4.5

In [198]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [199]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [200]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [201]:
df.skew()

one    1.664846
two         NaN
dtype: float64

In [202]:
df.diff()

one  two
a  NaN  NaN
b  5.7  NaN
c  NaN  NaN
d  NaN  NaN

In [204]:
df.fillna(0).diff()

one  two
a   NaN  NaN
b  5.70 -4.5
c -7.10  4.5
d  0.75 -1.3

In [205]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close']
for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
for ticker, data in all_data.items()})

ModuleNotFoundError: No module named 'pandas_datareader'